### ISSUE TITLE
Translation questions

### ISSUE THREAD

**Issue by Willem3141** [Deevad/peppercarrot_ep06_translation#1]
I committed and pushed a first version of the Dutch translation. While translating (from the English version) I had a few questions about page P04:
- in Coriander's text, **Technologist's Union**: is this a country or an organization of people?
- in Carrot's text, **Squirrel's End**: I suppose this is the village/town, right?

By the way: this is a great episode again, I can't wait to see the finished version :smiley:

**Comment by agryson** [comment]
From the original French it would be a country/conglomeration of countries, like the European Union or United Kingdom.

"Squirrel's End" refers to the whole forest / area of forest.

**Comment by agryson** [comment]
(Both of those are judging from the original French but correct me if I'm wrong, in which case I can then update the English version)

**Comment by Deevad** [comment]
@Willem3141  thanks for pushing it. 
@agryson is right ; ( @agryson I just gave you push access to )

**Technologist's Union** refer to a group of countries over seas with a similar level of technology than the Victorian era in our world (Industrial revolution) ; based on steam and a bit of magic. The main city of the Technologist's Union will appear on future episode. It will be my 'device' when I'll need to talk about pollution, or stupid technology.

**Squirrel's End**  yes, the whole forest not far from Komona, the flying city.  The first panel of episode 2 shows the house of Pepper in the forest of Squirrel's End " http://www.peppercarrot.com/el/article237/episode-2-rainbow-potions "  . You can find a fun association of words to name it. It can sounds from country-side, far away, in a hole nobody ever visit. 
French version is 'bout-un-cureuil' with Ecureuil=Squirel half mentionned in it ; to sounds a bit like 'un cul' in the middle of the name ( mean ' a ass' , but hidden in the words ). To make it sounds ridiculous. Pepper lives in the forest in the middle of nowhere  .   :)

**Comment by Willem3141** [comment]
Thanks for the clarifications! I thought of a Dutch pun like Bout-un-Cureuil for the name of the forest (_Eikhoornwoud_ = _eik_ (oak) + _eekhoorn_ + (squirrel) + _woud_ (forest) - it is not really literal, but I can't find a funny-sounding name with "bout/end" in it), and updated the translation.

**Comment by Deevad** [comment]
Hey, sorry for no news @Willem3141, I didn't slept the last nights before the release and I totally forgot to reply here. Thank you for the translation ready at release time !

**Comment by Willem3141** [comment]
No problem, it was fun to do :smile:
