### ISSUE TITLE
[it] "quà" --> "qua"

### ISSUE THREAD

**Issue by Deevad** [Deevad/peppercarrot_ep06_translation#22]
@cgand I had a feedback this morning about a typo in the Italian version. Can you tell me if the feedback is right ? (I can fix it, but I have no idea if it's correct)
From http://www.peppercarrot.com/article271/episode-6-the-potion-contest/#c1455273043-1
to quote:

> "Just a thing: in the italian translation it's mispelled: you wrote "quà", but it should be "qua" instead. "

**Comment by cgand** [comment]
Yes, feedback is right, sorry.

**Comment by Deevad** [comment]
no problem @cgand :-) I'll fix it this week end!
